// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var sumOfEven = 0;
var firstNum = 0;
var secondNum = 1;

for (var currentNum = firstNum + secondNum; currentNum < 4000000; currentNum = firstNum + secondNum) {
    if (currentNum % 2 === 0) {
      sumOfEven = sumOfEven + currentNum;
    }
  firstNum = secondNum;
  secondNum = currentNum;
}

console.log(sumOfEven);

// answer is 4613732
